wordpress:
  build: .
  hostname: ciudatos
  domainname: .com
  volumes:
    - ../data-mount-wordpress/var-lib-mysql/mysql:/var/lib/mysql/
    - ../data-mount-wordpress/var-www:/var/www
  ports:
    - "4545:80"
